export const eventsData1 = [
  {
    date: "2023-11-16",
    events: [
      {
        title: "Woman Of",
        description: "Drama written and directed by Michal Englert",
        venue: "Luxe Screen 1",
        eventDate: "2023-11-16 10:00:00",
        totalSeats: 60,
        price: 120,
        eventType: "film",
      },
      {
        title: "Cinematography and Stills",
        description: "Workshop by cinematographer and director Priyadarshan",
        venue: "MGR Institute Lecture Hall 2",
        eventDate: "2023-11-16 14:00:00",
        totalSeats: 40,
        price: 250,
        eventType: "workshop",
      },
      {
        title: "Sanaa",
        description: "2022 drama written and directed by Sudhanshu Saria",
        venue: "Luxe Screen 1",
        eventDate: "2023-11-16 14:00:00",
        totalSeats: 60,
        price: 140,
        eventType: "film",
      },
      {
        title: "Pookkaalam",
        description: "2023 romantic drama directed by Ganesh Raj",
        venue: "Luxe Screen 3",
        eventDate: "2023-11-16 18:00:00",
        totalSeats: 60,
        price: 140,
        eventType: "film",
      },
    ],
  },
  {
    date: "2023-11-17",
    events: [
      {
        title: "The Other Widow",
        description: "Mystery thriller directed by Maayan Rypp",
        venue: "Luxe Screen 1",
        eventDate: "2023-11-17 10:00:00",
        totalSeats: 60,
        price: 140,
        eventType: "film",
      },
      {
        title: "Party Of Fools",
        description: "Drama written and directed by Michal Englert",
        venue: "Luxe Screen 5",
        eventDate: "2023-11-17 14:00:00",
        totalSeats: 60,
        price: 140,
        eventType: "film",
      },
      {
        title: "Makeup",
        description: "Workshop by veteran makeup-artist K. M. Sarathkumar",
        venue: "MGR Institute Lecture Hall 2",
        eventDate: "2023-11-17 14:00:00",
        totalSeats: 30,
        price: 250,
        eventType: "workshop",
      },
      {
        title: "Neela Nira Sooriyan",
        description: "Tamil Drama written and directed by Samyuktha Vijayan",
        venue: "Luxe Screen 3",
        eventDate: "2023-11-17 18:00:00",
        totalSeats: 60,
        price: 140,
        eventType: "film",
      },
    ],
  },
  {
    date: "2023-11-18",
    events: [
      {
        title: "Measures Of Men",
        description: "2023 German drama film directed by Lars Kraume",
        venue: "Luxe Screen 2",
        eventDate: "2023-11-18 14:00:00",
        totalSeats: 60,
        price: 140,
        eventType: "film",
      },
      {
        title: "Acting and Comedy",
        description: "Workshop by veteran actor Naasar",
        venue: "MGR Institute Lecture Hall 2",
        eventDate: "2023-11-18 14:00:00",
        totalSeats: 50,
        price: 350,
        eventType: "workshop",
      },
      {
        title: "Lubo",
        description:
          "2023 Italian-Swiss drama film directed by Giorgio Diritti",
        venue: "Luxe Screen 1",
        eventDate: "2023-11-18 18:00:00",
        totalSeats: 60,
        price: 140,
        eventType: "film",
      },
      {
        title: "Press Meet",
        description: "International Entries Press Meet",
        venue: "Banquet Hall, The Accord",
        eventDate: "2023-11-18 18:00:00",
        totalSeats: 0,
        price: 0,
        eventType: "press",
      },
    ],
  },
  {
    date: "2023-11-19",
    events: [
      {
        title: "Aattam",
        description: "Malayalam movie written and directed by Anand Ekarshi",
        venue: "Luxe Screen 7",
        eventDate: "2023-11-19 10:00:00",
        totalSeats: 60,
        price: 140,
        eventType: "film",
      },
      {
        title: "Press Meet",
        description: "Indian Entries Press Meet",
        venue: "Banquet Hall, The Accord",
        eventDate: "2023-11-19 14:00:00",
        totalSeats: 0,
        price: 0,
        eventType: "press",
      },
      {
        title: "Makeup",
        description: "Workshop by veteran makeup-artist K. M. Sarathkumar",
        venue: "MGR Institute Lecture Hall 2",
        eventDate: "2023-11-19 14:00:00",
        totalSeats: 90,
        price: 330,
        eventType: "workshop",
      },
      {
        title: "Press Meet",
        description: "Indian Entries Press Meet",
        venue: "Banquet Hall, The Accord",
        eventDate: "2023-11-19 16:00:00",
        totalSeats: 0,
        price: 0,
        eventType: "press",
      },
    ],
  },
  {
    date: "2023-11-20",
    events: [
      {
        id: 4,
        title: "Awards Ceremony",
        description:
          "Awards Ceremony for winning entries, special awards and Life Time Achievement award",
        venue: "Nehru Indoor Stadium, Chennai",
        eventDate: "2023-11-20 18:00:00",
        totalSeats: 3000,
        price: 2500,
        eventType: "awards",
      },
    ],
  },
];
