export const eventsData = [
  {
    title: "Woman Of",
    description: "Drama written and directed by Michal Englert",
    eventColorCode: "#eceff4",
    icon: "/icons/events/icon-screen-dark.svg",
    venue: "Luxe Screen 1",
    iconAlt: "Screen Icon",
    eventDate: "2023-11-16 10:00:00",
    totalSeats: 60,
    price: 120,
  },
  {
    title: "Cinematography and Stills",
    description: "Workshop by cinematographer and director Priyadarshan",
    eventColorCode: "#fee1d9",
    icon: "/icons/events/icon-camera-dark.svg",
    venue: "MGR Institute Lecture Hall 2",
    iconAlt: "Camera Icon",

    eventDate: "2023-11-16 14:00:00",
    totalSeats: 40,
    price: 250,
  },
  {
    title: "Sanaa",
    description: "2022 drama written and directed by Sudhanshu Saria",
    eventColorCode: "#eceff4",
    icon: "/icons/events/icon-screen-dark.svg",
    iconAlt: "Screen Icon",
    venue: "Luxe Screen 1",
    eventDate: "2023-11-16 14:00:00",
    totalSeats: 60,
    price: 140,
  },
  {
    title: "Pookkaalam",
    description: "2023 romantic drama directed by Ganesh Raj",
    eventColorCode: "#eceff4",
    icon: "/icons/events/icon-screen-dark.svg",
    venue: "Luxe Screen 3",
    iconAlt: "Camera Icon",
    eventDate: "2023-11-16 18:00:00",
    totalSeats: 60,
    price: 140,
  },
  {
    title: "The Other Widow",
    description: "Mystery thriller directed by Maayan Rypp",
    eventColorCode: "#eceff4",
    icon: "/icons/events/icon-screen-dark.svg",
    venue: "Luxe Screen 1",
    iconAlt: "Screen Icon",
    eventDate: "2023-11-17 10:00:00",
    totalSeats: 60,
    price: 140,
  },
  {
    title: "Party Of Fools",
    description: "Drama written and directed by Michal Englert",
    eventColorCode: "#eceff4",
    icon: "/icons/events/icon-screen-dark.svg",
    venue: "Luxe Screen 5",
    iconAlt: "Screen Icon",
    eventDate: "2023-11-17 14:00:00",
    totalSeats: 60,
    price: 140,
  },
  {
    title: "Makeup",
    description: "Workshop by veteran makeup-artist K. M. Sarathkumar",
    eventColorCode: "#fee1d9",
    icon: "/icons/events/icon-camera-dark.svg",
    venue: "MGR Institute Lecture Hall 2",
    iconAlt: "Camera Icon",
    eventDate: "2023-11-17 14:00:00",
    totalSeats: 30,
    price: 250,
  },
  {
    title: "Neela Nira Sooriyan",
    description: "Tamil Drama written and directed by Samyuktha Vijayan",
    eventColorCode: "#eceff4",
    icon: "/icons/events/icon-screen-dark.svg",
    venue: "Luxe Screen 3",
    iconAlt: "Screen Icon",
    eventDate: "2023-11-17 18:00:00",
    totalSeats: 60,
    price: 140,
  },
  {
    title: "Measures Of Men",
    description: "2023 German drama film directed by Lars Kraume",
    eventColorCode: "#eceff4",
    icon: "/icons/events/icon-screen-dark.svg",
    iconAlt: "Screen Icon",
    venue: "Luxe Screen 1",
    eventDate: "2023-11-18 10:00:00",
    totalSeats: 60,
    price: 140,
  },

  {
    title: "Measures Of Men",
    description: "2023 German drama film directed by Lars Kraume",
    eventColorCode: "#eceff4",
    icon: "/icons/events/icon-screen-dark.svg",
    venue: "Luxe Screen 2",
    iconAlt: "Screen Icon",
    eventDate: "2023-11-18 14:00:00",
    totalSeats: 60,
    price: 140,
  },
  {
    title: "Acting and Comedy",
    description: "Workshop by veteran actor Naasar",
    eventColorCode: "#fee1d9",
    icon: "/icons/events/icon-camera-dark.svg",
    venue: "MGR Institute Lecture Hall 2",
    iconAlt: "Camera Icon",

    eventDate: "2023-11-18 14:00:00",
    totalSeats: 50,
    price: 350,
  },
  {
    title: "Lubo",
    description: "2023 Italian-Swiss drama film directed by Giorgio Diritti",
    eventColorCode: "#eceff4",
    icon: "/icons/events/icon-screen-dark.svg",
    venue: "Luxe Screen 1",
    iconAlt: "Screen Icon",

    eventDate: "2023-11-18 18:00:00",
    totalSeats: 60,
    price: 140,
  },
  {
    title: "Press Meet",
    description: "International Entries Press Meet",
    eventColorCode: "#dfdff9",
    icon: "/icons/events/icon-press-dark.svg",
    venue: "Banquet Hall, The Accord",
    iconAlt: "press meet Icon",

    eventDate: "2023-11-18 18:00:00",
    totalSeats: 60,
    price: 140,
  },
  {
    title: "Aattam",
    description: "Malayalam movie written and directed by Anand Ekarshi",
    eventColorCode: "#eceff4",
    icon: "/icons/events/icon-screen-dark.svg",
    venue: "Luxe Screen 7",
    iconAlt: "Screen Icon",

    eventDate: "2023-11-19 10:00:00",
    totalSeats: 60,
    price: 140,
  },
  {
    title: "Press Meet",
    description: "Indian Entries Press Meet",
    eventColorCode: "#dfdff9",
    icon: "/icons/events/icon-press-dark.svg",
    venue: "Banquet Hall, The Accord",
    iconAlt: "Microphone Icon",
    eventDate: "2023-11-19 14:00:00",
    totalSeats: 0,
    price: 0,
  },
  {
    title: "Makeup",
    description: "Workshop by veteran makeup-artist K. M. Sarathkumar",
    eventColorCode: "#fee1d9",
    icon: "/icons/events/icon-camera-dark.svg",
    venue: "MGR Institute Lecture Hall 2",
    iconAlt: "Camera Icon",

    eventDate: "2023-11-19 14:00:00",
    totalSeats: 90,
    price: 330,
  },
  {
    title: "Press Meet",
    description: "Indian Entries Press Meet",
    eventColorCode: "#dfdff9",
    icon: "/icons/events/icon-press-dark.svg",
    venue: "Banquet Hall, The Accord",
    iconAlt: "Microphone Icon",

    eventDate: "2023-11-19 16:00:00",
    totalSeats: 0,
    price: 0,
  },
  {
    id: 4,
    title: "Awards Ceremony",
    description:
      "Awards Ceremony for winning entries, special awards and Life Time Achievement award",
    eventColorCode: "#d8f1ee",
    icon: "/icons/events/icon-medal-dark.svg",
    venue: "Nehru Indoor Stadium, Chennai",
    iconAlt: "Award Icon",

    eventDate: "2023-11-20 18:00:00",
    totalSeats: 3000,
    price: 2500,
  },
];
